import { NextRequest, NextResponse } from "next/server";
import prisma from "@/lib/db";
import { getSession, isAgencyAdmin } from "@/lib/auth";
import { startOfDay, endOfDay } from "date-fns";

// GET /api/tasks - Get tasks for current user
export async function GET(request: NextRequest) {
  try {
    const session = await getSession();
    if (!session) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const { searchParams } = new URL(request.url);
    const date = searchParams.get("date");
    const completed = searchParams.get("completed");

    const where: any = {};

    // Non-admins only see their own tasks
    if (!isAgencyAdmin(session.role)) {
      where.userId = session.id;
    }

    if (date === "today") {
      const today = new Date();
      where.dueDate = {
        lte: endOfDay(today),
      };
      where.completed = false;
    } else if (date) {
      const targetDate = new Date(date);
      where.dueDate = {
        gte: startOfDay(targetDate),
        lte: endOfDay(targetDate),
      };
    }

    if (completed !== null) {
      where.completed = completed === "true";
    }

    const tasks = await prisma.task.findMany({
      where,
      include: {
        lead: {
          select: {
            id: true,
            firstName: true,
            lastName: true,
            primaryEmail: true,
            primaryPhone: true,
            interestedVehicle: true,
            stage: true,
          },
        },
        user: {
          select: { id: true, name: true },
        },
      },
      orderBy: [
        { completed: "asc" },
        { dueDate: "asc" },
        { createdAt: "asc" },
      ],
    });

    // Group tasks by status
    const overdue: typeof tasks = [];
    const today: typeof tasks = [];
    const upcoming: typeof tasks = [];
    const completedTasks: typeof tasks = [];

    const now = new Date();
    const todayStart = startOfDay(now);
    const todayEnd = endOfDay(now);

    for (const task of tasks) {
      if (task.completed) {
        completedTasks.push(task);
      } else if (task.dueDate < todayStart) {
        overdue.push(task);
      } else if (task.dueDate <= todayEnd) {
        today.push(task);
      } else {
        upcoming.push(task);
      }
    }

    return NextResponse.json({
      tasks,
      grouped: {
        overdue,
        today,
        upcoming,
        completed: completedTasks,
      },
    });
  } catch (error) {
    console.error("Get tasks error:", error);
    return NextResponse.json({ error: "Failed to fetch tasks" }, { status: 500 });
  }
}

// POST /api/tasks - Create task
export async function POST(request: NextRequest) {
  try {
    const session = await getSession();
    if (!session) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const data = await request.json();

    if (!data.leadId) {
      return NextResponse.json({ error: "Lead ID required" }, { status: 400 });
    }

    const lead = await prisma.lead.findUnique({
      where: { id: data.leadId },
      select: { dealershipId: true },
    });

    if (!lead) {
      return NextResponse.json({ error: "Lead not found" }, { status: 404 });
    }

    const task = await prisma.task.create({
      data: {
        leadId: data.leadId,
        userId: data.userId || session.id,
        dealershipId: lead.dealershipId,
        taskType: data.taskType || "custom",
        title: data.title,
        description: data.description,
        dueDate: new Date(data.dueDate),
        dueTime: data.dueTime ? new Date(`1970-01-01T${data.dueTime}`) : null,
        isAutoGenerated: false,
      },
      include: {
        lead: {
          select: {
            id: true,
            firstName: true,
            lastName: true,
          },
        },
      },
    });

    return NextResponse.json({ task }, { status: 201 });
  } catch (error) {
    console.error("Create task error:", error);
    return NextResponse.json({ error: "Failed to create task" }, { status: 500 });
  }
}
