import prisma from "@/lib/db";
import { LeadStage, FOLLOW_UP_DELAYS, MAX_ATTEMPTS, getStageConfig } from "@/types";
import { addDays } from "date-fns";

/**
 * Calculate win probability based on stage
 */
export function getWinProbability(stage: LeadStage): number {
  return getStageConfig(stage).winProbability;
}

/**
 * Calculate next follow-up date based on attempt count
 */
export function calculateNextFollowUp(attemptCount: number): Date | null {
  if (attemptCount >= MAX_ATTEMPTS - 1) return null;

  const delayDays = FOLLOW_UP_DELAYS[attemptCount] || FOLLOW_UP_DELAYS[FOLLOW_UP_DELAYS.length - 1];
  return addDays(new Date(), delayDays);
}

/**
 * Create a new lead with initial follow-up task
 */
export async function createLead(data: {
  dealershipId: string;
  assignedToId?: string;
  firstName?: string;
  lastName?: string;
  primaryEmail?: string;
  primaryPhone?: string;
  source?: string;
  interestedVehicle?: string;
  notes?: string;
  city?: string;
  state?: string;
  zip?: string;
  metaCampaignId?: string;
  metaAdsetId?: string;
  metaAdId?: string;
}) {
  const { dealershipId, assignedToId, ...leadData } = data;

  // Create lead
  const lead = await prisma.lead.create({
    data: {
      dealershipId,
      assignedToId,
      ...leadData,
      source: leadData.source as any,
      stage: "new_lead",
      winProbability: 0.10,
      nextFollowUpAt: new Date(), // Immediate follow-up
      attemptCount: 0,
    },
  });

  // Create initial follow-up task if assigned
  if (assignedToId) {
    await prisma.task.create({
      data: {
        leadId: lead.id,
        userId: assignedToId,
        dealershipId,
        taskType: "follow_up_call",
        title: "Initial contact - Attempt 1 of 5",
        dueDate: new Date(),
        isAutoGenerated: true,
        attemptNumber: 1,
      },
    });
  }

  // Log activity
  await prisma.activity.create({
    data: {
      leadId: lead.id,
      activityType: "stage_changed",
      details: {
        oldStage: null,
        newStage: "new_lead",
        source: "lead_created",
      },
    },
  });

  return lead;
}

/**
 * Handle follow-up attempt result
 */
export async function handleFollowUpResult(
  leadId: string,
  userId: string,
  result: "no_response" | "interested" | "not_interested"
) {
  const lead = await prisma.lead.findUnique({
    where: { id: leadId },
    include: { dealership: true },
  });

  if (!lead) throw new Error("Lead not found");

  if (result === "interested") {
    // Move to interested stage
    await prisma.lead.update({
      where: { id: leadId },
      data: {
        stage: "interested",
        winProbability: 0.20,
        attemptCount: 0,
        nextFollowUpAt: null,
        lastAttemptAt: new Date(),
      },
    });

    await prisma.activity.create({
      data: {
        leadId,
        userId,
        activityType: "stage_changed",
        details: {
          oldStage: lead.stage,
          newStage: "interested",
          reason: "customer_responded_interested",
        },
      },
    });
  } else if (result === "not_interested") {
    // Move to lost
    await prisma.lead.update({
      where: { id: leadId },
      data: {
        stage: "lost",
        winProbability: 0,
        closedAt: new Date(),
        nextFollowUpAt: null,
        lastAttemptAt: new Date(),
      },
    });

    await prisma.activity.create({
      data: {
        leadId,
        userId,
        activityType: "stage_changed",
        details: {
          oldStage: lead.stage,
          newStage: "lost",
          reason: "customer_not_interested",
        },
      },
    });
  } else if (result === "no_response") {
    const newAttemptCount = lead.attemptCount + 1;

    if (newAttemptCount >= MAX_ATTEMPTS) {
      // Max attempts reached - move to lost_unanswered
      await prisma.lead.update({
        where: { id: leadId },
        data: {
          stage: "lost_unanswered",
          winProbability: 0,
          attemptCount: newAttemptCount,
          closedAt: new Date(),
          nextFollowUpAt: null,
          lastAttemptAt: new Date(),
        },
      });

      await prisma.activity.create({
        data: {
          leadId,
          userId,
          activityType: "stage_changed",
          details: {
            oldStage: lead.stage,
            newStage: "lost_unanswered",
            reason: "max_attempts_reached",
            attemptCount: newAttemptCount,
          },
        },
      });
    } else {
      // Schedule next follow-up
      const nextFollowUp = calculateNextFollowUp(lead.attemptCount);

      await prisma.lead.update({
        where: { id: leadId },
        data: {
          attemptCount: newAttemptCount,
          nextFollowUpAt: nextFollowUp,
          lastAttemptAt: new Date(),
        },
      });

      // Create next follow-up task
      if (nextFollowUp && lead.assignedToId) {
        await prisma.task.create({
          data: {
            leadId,
            userId: lead.assignedToId,
            dealershipId: lead.dealershipId,
            taskType: "follow_up_call",
            title: `Follow-up call - Attempt ${newAttemptCount + 1} of ${MAX_ATTEMPTS}`,
            dueDate: nextFollowUp,
            isAutoGenerated: true,
            attemptNumber: newAttemptCount + 1,
          },
        });
      }

      await prisma.activity.create({
        data: {
          leadId,
          userId,
          activityType: "call_missed",
          details: {
            attemptNumber: newAttemptCount,
            nextFollowUp: nextFollowUp?.toISOString(),
          },
        },
      });
    }
  }
}

/**
 * Change lead stage with activity logging
 */
export async function changeLeadStage(
  leadId: string,
  userId: string,
  newStage: LeadStage
) {
  const lead = await prisma.lead.findUnique({
    where: { id: leadId },
  });

  if (!lead) throw new Error("Lead not found");

  const stageConfig = getStageConfig(newStage);

  const updateData: any = {
    stage: newStage,
    winProbability: stageConfig.winProbability,
  };

  // If moving to a won or lost stage, set closedAt
  if (newStage.startsWith("won_") || newStage.startsWith("lost")) {
    updateData.closedAt = new Date();
  }

  // Clear follow-up if moving past new_lead
  if (newStage !== "new_lead") {
    updateData.nextFollowUpAt = null;
  }

  await prisma.lead.update({
    where: { id: leadId },
    data: updateData,
  });

  await prisma.activity.create({
    data: {
      leadId,
      userId,
      activityType: "stage_changed",
      details: {
        oldStage: lead.stage,
        newStage,
      },
    },
  });
}

/**
 * Check for duplicate leads
 */
export async function findDuplicates(
  dealershipId: string,
  email?: string,
  phone?: string
) {
  if (!email && !phone) return [];

  const conditions: any[] = [];

  if (email) {
    conditions.push(
      { primaryEmail: email },
      { alternateEmails: { has: email } }
    );
  }

  if (phone) {
    const normalizedPhone = phone.replace(/\D/g, "");
    conditions.push(
      { primaryPhone: phone },
      { primaryPhone: normalizedPhone },
      { alternatePhones: { has: phone } },
      { alternatePhones: { has: normalizedPhone } }
    );
  }

  return prisma.lead.findMany({
    where: {
      dealershipId,
      OR: conditions,
    },
    select: {
      id: true,
      firstName: true,
      lastName: true,
      primaryEmail: true,
      primaryPhone: true,
      stage: true,
      createdAt: true,
    },
  });
}
