import { NextRequest, NextResponse } from "next/server";
import prisma from "@/lib/db";
import { getSession } from "@/lib/auth";
import { handleFollowUpResult } from "@/lib/leads";

// PUT /api/tasks/[id] - Update task
export async function PUT(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const session = await getSession();
    if (!session) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const { id } = await params;
    const data = await request.json();

    const existing = await prisma.task.findUnique({
      where: { id },
      select: { userId: true, leadId: true, isAutoGenerated: true, attemptNumber: true },
    });

    if (!existing) {
      return NextResponse.json({ error: "Task not found" }, { status: 404 });
    }

    // Handle task completion with follow-up outcome
    if (data.completed && data.outcome) {
      // Mark task as completed
      await prisma.task.update({
        where: { id },
        data: {
          completed: true,
          completedAt: new Date(),
        },
      });

      // Handle follow-up logic if this is an auto-generated follow-up task
      if (existing.isAutoGenerated && existing.attemptNumber) {
        await handleFollowUpResult(existing.leadId, session.id, data.outcome);
      } else {
        // Log activity for manual task completion
        await prisma.activity.create({
          data: {
            leadId: existing.leadId,
            userId: session.id,
            activityType: "note_added",
            details: {
              type: "task_completed",
              taskId: id,
              outcome: data.outcome,
            },
          },
        });
      }

      const task = await prisma.task.findUnique({
        where: { id },
        include: {
          lead: {
            select: {
              id: true,
              firstName: true,
              lastName: true,
              stage: true,
            },
          },
        },
      });

      return NextResponse.json({ task });
    }

    // Regular update
    const updateData: any = {};

    if (data.title !== undefined) updateData.title = data.title;
    if (data.description !== undefined) updateData.description = data.description;
    if (data.dueDate !== undefined) updateData.dueDate = new Date(data.dueDate);
    if (data.dueTime !== undefined) updateData.dueTime = data.dueTime ? new Date(`1970-01-01T${data.dueTime}`) : null;
    if (data.completed !== undefined) {
      updateData.completed = data.completed;
      updateData.completedAt = data.completed ? new Date() : null;
    }

    const task = await prisma.task.update({
      where: { id },
      data: updateData,
      include: {
        lead: {
          select: {
            id: true,
            firstName: true,
            lastName: true,
          },
        },
      },
    });

    return NextResponse.json({ task });
  } catch (error) {
    console.error("Update task error:", error);
    return NextResponse.json({ error: "Failed to update task" }, { status: 500 });
  }
}

// DELETE /api/tasks/[id]
export async function DELETE(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const session = await getSession();
    if (!session) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const { id } = await params;

    const existing = await prisma.task.findUnique({
      where: { id },
      select: { userId: true, isAutoGenerated: true },
    });

    if (!existing) {
      return NextResponse.json({ error: "Task not found" }, { status: 404 });
    }

    // Don't allow deleting auto-generated tasks
    if (existing.isAutoGenerated) {
      return NextResponse.json(
        { error: "Cannot delete auto-generated tasks" },
        { status: 400 }
      );
    }

    await prisma.task.delete({ where: { id } });

    return NextResponse.json({ success: true });
  } catch (error) {
    console.error("Delete task error:", error);
    return NextResponse.json({ error: "Failed to delete task" }, { status: 500 });
  }
}
