"use client";

import { useEffect, useState } from "react";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { format } from "date-fns";

interface Lead {
  id: string;
  firstName: string | null;
  lastName: string | null;
  primaryEmail: string | null;
  primaryPhone: string | null;
  interestedVehicle: string | null;
  stage: string;
}

interface Task {
  id: string;
  title: string;
  description: string | null;
  dueDate: string;
  taskType: string;
  attemptNumber: number | null;
  isAutoGenerated: boolean;
  completed: boolean;
  lead: Lead;
}

interface GroupedTasks {
  overdue: Task[];
  today: Task[];
  upcoming: Task[];
  completed: Task[];
}

export default function MyDayPage() {
  const [tasks, setTasks] = useState<GroupedTasks | null>(null);
  const [loading, setLoading] = useState(true);
  const [completingTask, setCompletingTask] = useState<string | null>(null);

  const fetchTasks = async () => {
    try {
      const response = await fetch("/api/tasks?date=today");
      const data = await response.json();
      setTasks(data.grouped);
    } catch (error) {
      console.error("Failed to fetch tasks:", error);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchTasks();
  }, []);

  const handleComplete = async (taskId: string, outcome: string) => {
    setCompletingTask(taskId);
    try {
      await fetch(`/api/tasks/${taskId}`, {
        method: "PUT",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ completed: true, outcome }),
      });
      await fetchTasks();
    } catch (error) {
      console.error("Failed to complete task:", error);
    } finally {
      setCompletingTask(null);
    }
  };

  const getLeadName = (lead: Lead) => {
    if (lead.firstName || lead.lastName) {
      return `${lead.firstName || ""} ${lead.lastName || ""}`.trim();
    }
    return lead.primaryEmail || lead.primaryPhone || "Unknown";
  };

  const TaskCard = ({ task }: { task: Task }) => {
    const [showOutcome, setShowOutcome] = useState(false);

    return (
      <Card className="mb-3">
        <div className="flex items-start justify-between">
          <div className="flex-1">
            <div className="flex items-center gap-2 mb-1">
              <h3 className="font-medium text-gray-900">{getLeadName(task.lead)}</h3>
              {task.isAutoGenerated && (
                <Badge variant="blue" size="sm">Auto</Badge>
              )}
            </div>
            <p className="text-sm text-gray-600 mb-2">{task.title}</p>
            <div className="flex flex-wrap gap-2 text-sm text-gray-500">
              {task.lead.primaryPhone && (
                <a
                  href={`tel:${task.lead.primaryPhone}`}
                  className="flex items-center gap-1 hover:text-blue-600"
                >
                  <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M3 5a2 2 0 012-2h3.28a1 1 0 01.948.684l1.498 4.493a1 1 0 01-.502 1.21l-2.257 1.13a11.042 11.042 0 005.516 5.516l1.13-2.257a1 1 0 011.21-.502l4.493 1.498a1 1 0 01.684.949V19a2 2 0 01-2 2h-1C9.716 21 3 14.284 3 6V5z" />
                  </svg>
                  {task.lead.primaryPhone}
                </a>
              )}
              {task.lead.primaryEmail && (
                <a
                  href={`mailto:${task.lead.primaryEmail}`}
                  className="flex items-center gap-1 hover:text-blue-600"
                >
                  <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M3 8l7.89 5.26a2 2 0 002.22 0L21 8M5 19h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z" />
                  </svg>
                  {task.lead.primaryEmail}
                </a>
              )}
            </div>
            {task.lead.interestedVehicle && (
              <p className="text-sm text-gray-400 mt-1">
                Interested in: {task.lead.interestedVehicle}
              </p>
            )}
          </div>

          <div className="ml-4">
            {!showOutcome ? (
              <div className="flex gap-2">
                <Button
                  size="sm"
                  variant="primary"
                  onClick={() => setShowOutcome(true)}
                  disabled={completingTask === task.id}
                >
                  Complete
                </Button>
              </div>
            ) : (
              <div className="flex flex-col gap-2">
                <Button
                  size="sm"
                  variant="primary"
                  onClick={() => handleComplete(task.id, "interested")}
                  loading={completingTask === task.id}
                >
                  Interested
                </Button>
                <Button
                  size="sm"
                  variant="secondary"
                  onClick={() => handleComplete(task.id, "no_response")}
                  loading={completingTask === task.id}
                >
                  No Answer
                </Button>
                <Button
                  size="sm"
                  variant="danger"
                  onClick={() => handleComplete(task.id, "not_interested")}
                  loading={completingTask === task.id}
                >
                  Not Interested
                </Button>
                <Button
                  size="sm"
                  variant="ghost"
                  onClick={() => setShowOutcome(false)}
                >
                  Cancel
                </Button>
              </div>
            )}
          </div>
        </div>
      </Card>
    );
  };

  if (loading) {
    return (
      <div className="flex items-center justify-center h-64">
        <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-blue-600" />
      </div>
    );
  }

  const totalTasks = (tasks?.overdue.length || 0) + (tasks?.today.length || 0);

  return (
    <div className="max-w-3xl mx-auto">
      <div className="mb-6">
        <h1 className="text-2xl font-bold text-gray-900">My Day</h1>
        <p className="text-gray-600">
          {totalTasks === 0
            ? "No tasks for today. Great job!"
            : `${totalTasks} task${totalTasks === 1 ? "" : "s"} to complete`}
        </p>
      </div>

      {tasks?.overdue && tasks.overdue.length > 0 && (
        <div className="mb-8">
          <h2 className="text-lg font-semibold text-red-600 mb-3 flex items-center gap-2">
            <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 8v4m0 4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
            </svg>
            Overdue ({tasks.overdue.length})
          </h2>
          {tasks.overdue.map((task) => (
            <TaskCard key={task.id} task={task} />
          ))}
        </div>
      )}

      {tasks?.today && tasks.today.length > 0 && (
        <div className="mb-8">
          <h2 className="text-lg font-semibold text-gray-900 mb-3">
            Today ({tasks.today.length})
          </h2>
          {tasks.today.map((task) => (
            <TaskCard key={task.id} task={task} />
          ))}
        </div>
      )}

      {tasks?.upcoming && tasks.upcoming.length > 0 && (
        <div className="mb-8">
          <h2 className="text-lg font-semibold text-gray-500 mb-3">
            Upcoming ({tasks.upcoming.length})
          </h2>
          {tasks.upcoming.map((task) => (
            <TaskCard key={task.id} task={task} />
          ))}
        </div>
      )}

      {totalTasks === 0 && (
        <Card className="text-center py-12">
          <svg className="w-16 h-16 mx-auto text-gray-300 mb-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
          </svg>
          <h3 className="text-lg font-medium text-gray-900 mb-2">All caught up!</h3>
          <p className="text-gray-500">You have no tasks scheduled for today.</p>
        </Card>
      )}
    </div>
  );
}
